export const TIMER_FOCUS_MINUTES = 1;
export const TIMER_SECONDS = 60;
export const TIMER_LONG_BREAK_MINUTES = 25;
export const TIMER_SHORT_BREAK_MINUTES = 25;
export const TIMER_TIME = TIMER_FOCUS_MINUTES + TIMER_SECONDS;

export const PROGRESS_BAR_INITIAL_VALUE = 100;
export const TIMER_TICK = 100 / TIMER_TIME;
